begin transaction;
insert into rds.server_dcinput select * from lds.server_dcinput;
insert into rds.server_dcoutput select * from lds.server_dcoutput;
insert into rds.server_dimension select * from lds.server_dimension;
insert into rds.server_product select * from lds.server_product;
insert into rds.server_prodbattery select * from lds.server_prodbattery;
insert into rds.server_entity select * from lds.server_entity;
insert into rds.server_certificationagency select * from lds.server_certificationagency;
insert into rds.server_checksum select * from lds.server_checksum;
insert into rds.server_firmware select * from lds.server_firmware;
insert into rds.server_prodcertification select * from lds.server_prodcertification;
insert into rds.server_product_ProdCertifications select * from lds.server_product_ProdCertifications;
insert into rds.server_prodcell select * from lds.server_prodcell;
insert into rds.server_prodglazing select * from lds.server_prodglazing;
insert into rds.server_moduleelectrating select * from lds.server_moduleelectrating;
insert into rds.server_prodmodule select * from lds.server_prodmodule;
insert into rds.server_prodmodule_ModuleElectRatings select * from lds.server_prodmodule_ModuleElectRatings;
insert into rds.server_sourcecountry select * from lds.server_sourcecountry;
insert into rds.server_product_SourceCountries select * from lds.server_product_SourceCountries;
--commit;
