# Generated by Django 4.1.5 on 2025-01-06 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token')),
                ('expires', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True)),
            ],
            bases=('authtoken.token',),
        ),
    ]
