# Generated by Django 6.0.2 on 2026-03-10 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_remove_product_proddatasheet_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='AlternativeIdentifiers',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='AlternativeIdentifiers',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='AlternativeIdentifiers',
        ),
        migrations.RemoveField(
            model_name='dcinput',
            name='MPPTs',
        ),
        migrations.RemoveField(
            model_name='dcoutput',
            name='PowerDCPeaks',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='Addresses',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='CreditRatings',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='PaymentMethods',
        ),
        migrations.RemoveField(
            model_name='firmware',
            name='Products',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='Comments',
        ),
        migrations.RemoveField(
            model_name='product',
            name='CommunicationStacks',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Packages',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ProdInstructions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ProdQualifications',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ProdSpecifications',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Warranties',
        ),
        migrations.AddField(
            model_name='address',
            name='Contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='server.contact'),
        ),
        migrations.AddField(
            model_name='address',
            name='Entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Addresses', to='server.entity'),
        ),
        migrations.AddField(
            model_name='checksum',
            name='Firmware',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='server.firmware'),
        ),
        migrations.AddField(
            model_name='comment',
            name='PaymentMethod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to='server.paymentmethod'),
        ),
        migrations.AddField(
            model_name='communicationstack',
            name='Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CommunicationStacks', to='server.product'),
        ),
        migrations.AddField(
            model_name='creditrating',
            name='Entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CreditRatings', to='server.entity'),
        ),
        migrations.AddField(
            model_name='dcinput',
            name='ProdBattery',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='server.prodbattery'),
        ),
        migrations.AddField(
            model_name='dcoutput',
            name='ProdBattery',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='server.prodbattery'),
        ),
        migrations.AddField(
            model_name='dimension',
            name='Package',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='server.package'),
        ),
        migrations.AddField(
            model_name='dimension',
            name='Product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='server.product'),
        ),
        migrations.AddField(
            model_name='firmware',
            name='ProdCertification',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='server.prodcertification'),
        ),
        migrations.AddField(
            model_name='location',
            name='Address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='server.address'),
        ),
        migrations.AddField(
            model_name='location',
            name='Scope',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='server.scope'),
        ),
        migrations.AddField(
            model_name='moduleelectrating',
            name='ProdModule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='server.prodmodule'),
        ),
        migrations.AddField(
            model_name='mppt',
            name='DCInput',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MPPTs', to='server.dcinput'),
        ),
        migrations.AddField(
            model_name='package',
            name='Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Packages', to='server.product'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='Entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PaymentMethods', to='server.entity'),
        ),
        migrations.AddField(
            model_name='powerdcpeak',
            name='DCOutput',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PowerDCPeaks', to='server.dcoutput'),
        ),
        migrations.AddField(
            model_name='prodcertification',
            name='Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='server.product'),
        ),
        migrations.AddField(
            model_name='prodglazing',
            name='ProdModule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='server.prodmodule'),
        ),
        migrations.AddField(
            model_name='prodinstruction',
            name='Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProdInstructions', to='server.product'),
        ),
        migrations.AddField(
            model_name='prodqualification',
            name='Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProdQualifications', to='server.product'),
        ),
        migrations.AddField(
            model_name='prodspecification',
            name='Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProdSpecifications', to='server.product'),
        ),
        migrations.AddField(
            model_name='scope',
            name='Comment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='server.comment'),
        ),
        migrations.AddField(
            model_name='sourcecountry',
            name='Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='server.product'),
        ),
        migrations.AddField(
            model_name='warranty',
            name='Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Warranties', to='server.product'),
        ),
        migrations.CreateModel(
            name='EntityAlternativeIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description_Value', models.CharField(blank=True, max_length=500)),
                ('Identifier_Value', models.CharField(blank=True, max_length=500)),
                ('IdentifierType_Value', models.CharField(blank=True, choices=[('DID', 'Decentralized Identifier'), ('DPP_EU', 'EU Digital Product Passport'), ('DUNS', 'DUNS'), ('FEIN', 'Federal Employer Identification Number'), ('LEI', 'Legal Entity Identifier'), ('Other', 'Other'), ('PEN', 'Private Enterprise Number'), ('ProdCode', 'ProdCode'), ('UEI', 'Unique Entity Identifier'), ('UPC', 'UPC'), ('UUID', 'UUID')], max_length=8)),
                ('SourceName_Value', models.CharField(blank=True, max_length=500)),
                ('Entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AlternativeIdentifiers', to='server.entity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentMethodAlternativeIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description_Value', models.CharField(blank=True, max_length=500)),
                ('Identifier_Value', models.CharField(blank=True, max_length=500)),
                ('IdentifierType_Value', models.CharField(blank=True, choices=[('DID', 'Decentralized Identifier'), ('DPP_EU', 'EU Digital Product Passport'), ('DUNS', 'DUNS'), ('FEIN', 'Federal Employer Identification Number'), ('LEI', 'Legal Entity Identifier'), ('Other', 'Other'), ('PEN', 'Private Enterprise Number'), ('ProdCode', 'ProdCode'), ('UEI', 'Unique Entity Identifier'), ('UPC', 'UPC'), ('UUID', 'UUID')], max_length=8)),
                ('SourceName_Value', models.CharField(blank=True, max_length=500)),
                ('PaymentMethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AlternativeIdentifiers', to='server.paymentmethod')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductAlternativeIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description_Value', models.CharField(blank=True, max_length=500)),
                ('Identifier_Value', models.CharField(blank=True, max_length=500)),
                ('IdentifierType_Value', models.CharField(blank=True, choices=[('DID', 'Decentralized Identifier'), ('DPP_EU', 'EU Digital Product Passport'), ('DUNS', 'DUNS'), ('FEIN', 'Federal Employer Identification Number'), ('LEI', 'Legal Entity Identifier'), ('Other', 'Other'), ('PEN', 'Private Enterprise Number'), ('ProdCode', 'ProdCode'), ('UEI', 'Unique Entity Identifier'), ('UPC', 'UPC'), ('UUID', 'UUID')], max_length=8)),
                ('SourceName_Value', models.CharField(blank=True, max_length=500)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AlternativeIdentifiers', to='server.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='AlternativeIdentifier',
        ),
    ]
