# Generated by Django 6.0.2 on 2026-03-10 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_copy_fk_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='Scope',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='firmware',
            name='Checksum',
        ),
        migrations.RemoveField(
            model_name='package',
            name='Dimension',
        ),
        migrations.RemoveField(
            model_name='prodbattery',
            name='DCInput',
        ),
        migrations.RemoveField(
            model_name='prodbattery',
            name='DCOutput',
        ),
        migrations.RemoveField(
            model_name='prodcertification',
            name='Firmware',
        ),
        migrations.RemoveField(
            model_name='prodmodule',
            name='ModuleElectRatings',
        ),
        migrations.RemoveField(
            model_name='prodmodule',
            name='ProdGlazing',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Dimension',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ProdCertifications',
        ),
        migrations.RemoveField(
            model_name='product',
            name='SourceCountries',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='Location',
        ),
        migrations.AlterField(
            model_name='address',
            name='Contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Address', to='server.contact'),
        ),
        migrations.AlterField(
            model_name='checksum',
            name='Firmware',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Checksum', to='server.firmware'),
        ),
        migrations.AlterField(
            model_name='dcinput',
            name='ProdBattery',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DCInput', to='server.prodbattery'),
        ),
        migrations.AlterField(
            model_name='dcoutput',
            name='ProdBattery',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DCOutput', to='server.prodbattery'),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='Package',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Dimension', to='server.package'),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='Product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Dimension', to='server.product'),
        ),
        migrations.AlterField(
            model_name='firmware',
            name='ProdCertification',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Firmware', to='server.prodcertification'),
        ),
        migrations.AlterField(
            model_name='location',
            name='Address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Location', to='server.address'),
        ),
        migrations.AlterField(
            model_name='location',
            name='Scope',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Location', to='server.scope'),
        ),
        migrations.AlterField(
            model_name='moduleelectrating',
            name='ProdModule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ModuleElectRatings', to='server.prodmodule'),
        ),
        migrations.AlterField(
            model_name='prodcertification',
            name='Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProdCertifications', to='server.product'),
        ),
        migrations.AlterField(
            model_name='prodglazing',
            name='ProdModule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProdGlazing', to='server.prodmodule'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='Comment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Scope', to='server.comment'),
        ),
        migrations.AlterField(
            model_name='sourcecountry',
            name='Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SourceCountries', to='server.product'),
        ),
    ]
