# Generated by Django 6.0.2 on 2026-03-12 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_remove_address_location_remove_comment_scope_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Contacts',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='Contacts',
        ),
        migrations.AddField(
            model_name='comment',
            name='Contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to='server.contact'),
        ),
        migrations.AddField(
            model_name='contact',
            name='Entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Contacts', to='server.entity'),
        ),
    ]
