# Generated by Django 6.0.2 on 2026-03-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_remove_comment_contacts_remove_entity_contacts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='CECProdCode_Value',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
