# Generated by Django 6.0.2 on 2026-04-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_feedbacksubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_email_to', models.CharField(blank=True, help_text='Comma-separated recipient email addresses. Blank = do not send email.', max_length=500)),
                ('feedback_email_from', models.EmailField(blank=True, help_text='From address. Must be verified in AWS SES.', max_length=254)),
                ('workato_webhook_url', models.URLField(blank=True, help_text='Workato recipe webhook URL. Blank = do not post to Workato.', max_length=500)),
                ('rate_limit_per_hour', models.PositiveIntegerField(default=3, help_text='Max submissions per IP per hour. 0 = disabled.')),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
