# Generated by Django 6.0.1 on 2026-02-14 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OBArrayOfObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OBElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=41, unique=True)),
                ('description', models.CharField(max_length=703)),
            ],
        ),
        migrations.CreateModel(
            name='OBItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=39, unique=True)),
                ('description', models.CharField(max_length=844)),
            ],
        ),
        migrations.CreateModel(
            name='OBPrimitive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=17, unique=True)),
                ('description', models.CharField(max_length=197)),
                ('is_array', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='OBArrayOfElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ob_taxonomy.obelement')),
            ],
        ),
        migrations.AddField(
            model_name='obelement',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ob_taxonomy.obitemtype'),
        ),
        migrations.CreateModel(
            name='OBItemTypeEnum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=96, unique=True)),
                ('label', models.CharField(max_length=56)),
                ('description', models.CharField(max_length=844)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'label'), name='unique_enum_name_and_label')],
            },
        ),
        migrations.AddField(
            model_name='obitemtype',
            name='enums',
            field=models.ManyToManyField(to='ob_taxonomy.obitemtypeenum'),
        ),
        migrations.CreateModel(
            name='OBItemTypeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=18, unique=True)),
                ('description', models.CharField(max_length=71)),
                ('enums', models.ManyToManyField(to='ob_taxonomy.obitemtypeenum')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ob_taxonomy.obitemtype')),
            ],
        ),
        migrations.AddField(
            model_name='obelement',
            name='item_type_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ob_taxonomy.obitemtypegroup'),
        ),
        migrations.CreateModel(
            name='OBItemTypeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=21)),
                ('label', models.CharField(max_length=39)),
                ('description', models.CharField(max_length=620)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'label'), name='unique_unit_name_and_label')],
            },
        ),
        migrations.AddField(
            model_name='obitemtypegroup',
            name='units',
            field=models.ManyToManyField(to='ob_taxonomy.obitemtypeunit'),
        ),
        migrations.AddField(
            model_name='obitemtype',
            name='units',
            field=models.ManyToManyField(to='ob_taxonomy.obitemtypeunit'),
        ),
        migrations.CreateModel(
            name='OBObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=41, unique=True)),
                ('description', models.CharField(max_length=703)),
                ('element_arrays', models.ManyToManyField(to='ob_taxonomy.obarrayofelement')),
                ('nested_objects', models.ManyToManyField(to='ob_taxonomy.obobject')),
                ('object_arrays', models.ManyToManyField(to='ob_taxonomy.obarrayofobject')),
                ('properties', models.ManyToManyField(to='ob_taxonomy.obelement')),
            ],
        ),
        migrations.AddField(
            model_name='obarrayofobject',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ob_taxonomy.obobject'),
        ),
        migrations.CreateModel(
            name='OBObjectComprisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('allOf', 'allOf'), ('anyOf', 'anyOf'), ('oneOf', 'oneOf')], default='allOf', max_length=5)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ob_taxonomy.obobject')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='obobjectcomposition_set', to='ob_taxonomy.obobject')),
            ],
        ),
        migrations.AddField(
            model_name='obobject',
            name='comprises',
            field=models.ManyToManyField(through='ob_taxonomy.OBObjectComprisal', to='ob_taxonomy.obobject'),
        ),
        migrations.CreateModel(
            name='OBTaxonomyElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=27, unique=True)),
                ('primitives', models.ManyToManyField(to='ob_taxonomy.obprimitive')),
            ],
        ),
        migrations.AddField(
            model_name='obelement',
            name='taxonomy_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ob_taxonomy.obtaxonomyelement'),
        ),
        migrations.AddConstraint(
            model_name='obobjectcomprisal',
            constraint=models.UniqueConstraint(fields=('method', 'target'), name='unique_object_comprisal_strategy'),
        ),
    ]
