# Generated by Django 6.0.2 on 2026-02-28 22:49

from django.db import migrations


class DataMigration:
    @staticmethod
    def forward(apps, schema_editor):
        raise NotImplementedError()

    @staticmethod
    def reverse(apps, schema_editor):
        raise NotImplementedError()

    @classmethod
    def forward_reverse(cls):
        return cls.forward, cls.reverse


class RenameOBElementProdDatasheetToProdDatasheetURL(DataMigration):
    @staticmethod
    def forward(apps, schema_editor):
        OBElement = apps.get_model('ob_taxonomy', 'OBElement')
        element = OBElement.objects.get(name='ProdDatasheet')
        element.name = 'ProdDatasheetURL'
        element.save()

    @staticmethod
    def reverse(apps, schema_editor):
        OBElement = apps.get_model('ob_taxonomy', 'OBElement')
        element = OBElement.objects.get(name='ProdDatasheetURL')
        element.name = 'ProdDatasheet'
        element.save()


class AddOBElementAttestationURLAndAddItToSourceCountry(DataMigration):
    @staticmethod
    def forward(apps, schema_editor):
        OBTaxonomyElement = apps.get_model('ob_taxonomy', 'OBTaxonomyElement')
        OBItemType = apps.get_model('ob_taxonomy', 'OBItemType')
        OBElement = apps.get_model('ob_taxonomy', 'OBElement')
        OBObject = apps.get_model('ob_taxonomy', 'OBObject')
        element = OBElement(
            name='AttestationURL',
            description="A URL to the attestation of a product's assigned cost percentage for country of manufacture",
            taxonomy_element=OBTaxonomyElement.objects.get(name='TaxonomyElementString'),
            item_type=OBItemType.objects.get(name='StringItemType'),
        )
        element.save()
        SourceCountry = OBObject.objects.get(name='SourceCountry')
        SourceCountry.properties.add(element)

    @staticmethod
    def reverse(apps, schema_editor):
        OBElement = apps.get_model('ob_taxonomy', 'OBElement')
        OBElement.objects.get(name='AttestationURL').delete()


class RenameItemTypeCountryToISOCountryItemType(DataMigration):
    @staticmethod
    def forward(apps, schema_editor):
        OBItemType = apps.get_model('ob_taxonomy', 'OBItemType')
        item_type = OBItemType.objects.get(name='Country')
        item_type.name = 'ISOCountryItemType'
        item_type.save()

    @staticmethod
    def reverse(apps, schema_editor):
        OBItemType = apps.get_model('ob_taxonomy', 'OBItemType')
        item_type = OBItemType.objects.get(name='ISOCountryItemType')
        item_type.name = 'Country'
        item_type.save()


def set_item_type(apps, element_name, item_type_name):
    OBItemType = apps.get_model('ob_taxonomy', 'OBItemType')
    OBElement = apps.get_model('ob_taxonomy', 'OBElement')
    item_type = OBItemType.objects.get(name=item_type_name)
    element = OBElement.objects.get(name=element_name)
    element.item_type = item_type
    element.save()


class SetItemTypeOfOBElementCountryOfManufactureToISOCountryItemType(DataMigration):
    @staticmethod
    def forward(apps, schema_editor):
        set_item_type(apps, 'CountryOfManufacture', 'ISOCountryItemType')

    @staticmethod
    def reverse(apps, schema_editor):
        set_item_type(apps, 'CountryOfManufacture', 'StringItemType')


class RenameOBElementCountryOfOwnershipforPFEToCountryOfOwnershipForPFE(DataMigration):
    @staticmethod
    def forward(apps, schema_editor):
        OBElement = apps.get_model('ob_taxonomy', 'OBElement')
        element = OBElement.objects.get(name='CountryOfOwnershipforPFE')
        element.name = 'CountryOfOwnershipForPFE'
        element.save()

    @staticmethod
    def reverse(apps, schema_editor):
        OBElement = apps.get_model('ob_taxonomy', 'OBElement')
        element = OBElement.objects.get(name='CountryOfOwnershipForPFE')
        element.name = 'CountryOfOwnershipforPFE'
        element.save()


class SetItemTypeOfOBElementCountryOfOwnershipForPFEToISOCountryItemType(DataMigration):
    @staticmethod
    def forward(apps, schema_editor):
        set_item_type(apps, 'CountryOfOwnershipForPFE', 'ISOCountryItemType')

    @staticmethod
    def reverse(apps, schema_editor):
        set_item_type(apps, 'CountryOfOwnershipForPFE', 'StringItemType')


class Migration(migrations.Migration):

    dependencies = [
        ('ob_taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(*RenameOBElementProdDatasheetToProdDatasheetURL.forward_reverse()),
        migrations.RunPython(*AddOBElementAttestationURLAndAddItToSourceCountry.forward_reverse()),
        migrations.RunPython(*RenameItemTypeCountryToISOCountryItemType.forward_reverse()),
        migrations.RunPython(*SetItemTypeOfOBElementCountryOfManufactureToISOCountryItemType.forward_reverse()),
        migrations.RunPython(*RenameOBElementCountryOfOwnershipforPFEToCountryOfOwnershipForPFE.forward_reverse()),
        migrations.RunPython(*SetItemTypeOfOBElementCountryOfOwnershipForPFEToISOCountryItemType.forward_reverse()),
    ]
